---
# Variablen spezifisch für MacBook Air Nodes (mba1, mba2)
# mac_tweaks Role läuft automatisch auf dieser Gruppe (ansible_architecture == "x86_64")

# Kernel-Module die beim Boot geladen werden sollen
mac_tweaks_kernel_modules:
  - apple-bce
  - apple-ibridge

# logind: Lid-close-Verhalten
mac_tweaks_logind_handle_lid_switch: "ignore"
mac_tweaks_logind_handle_lid_switch_external_power: "ignore"
