apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: furchert-ch
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/doemefu/furchert-ch
  ref:
    branch: main
  secretRef:
    name: furchert-ch-flux-auth
