---
- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
