name: "Ansible Lint"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r infra/requirements.yml
      - uses: ansible/ansible-lint@v26
