apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mcp-hub
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/doemefu/homelab-mcp-hub
  ref:
    branch: main
  secretRef:
    name: mcp-hub-flux-auth
